## Linear Algebra

### A matrix is a collection of numbers ordered in rows and columns
### each value in a matrix is an element of the matrix
### a matrix can only contain numbers symbols or expressions
### matrix size is denoted by m*n (m is the column and n is the row)

### Scalar: special kind of matrix with just one row and one column (reason why number sin algebra are refered to as scalars, they are objects with 0 dimensions

### Vectors: simplest algebraic object, example, matrix with just one columns and 3 rows, this makes a matrix a collection of vectors, there are row vectors and column vectors
### the length of a vector is the number of elements in a vector, a vectors length is designated as m

### Matrix-2 dimensions, Scalar-1 dimension, Vectors-no dimensions

### scalars and the geometrical idea of a point are 2 examples of objects with no dimensions
### vectors only have one dimension but they can be pointed in many directions
### for a line to cross the plane we do need 2 lines, and in this case we can use 2 vectors 

## The programming point of view for Linear Algebra
### the simplest most flexible way to work with matrices in Python is by using arrays

In [1]:
import numpy as np

## Scalars

In [2]:
s = 5
s

5

## Vectors

In [3]:
v = np.array([5, -2, 4])
v

array([ 5, -2,  4])

## Matrices

In [5]:
m = np.array([[5, 12, 6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## What is a tensor?
### a scalar has the smallest dimensionality and it is a 1 by 1,  can be though of as a vector of length 1 or a 1x1 matrix
### A tensor is a generalization of the concepts of scalars, vectors and matrices
### Tensors can be of rank 3 which means that their dimensions are k*m*n  so, a cllection of matrices
### Tensors can be stored in ndarrays and that is how we often deal with the issue

### Creating a tensor out of 2 matrices

In [6]:
m1 = np.array([[5,12,6], [-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [7]:
m2 = np.array([[9,8,7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [9]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [10]:
t.shape

(2, 2, 3)

### adding and subtracting matrices: the 3 matrices have to have the same dimensions
### same rules apply to vectors they have to have the same length

In [11]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [12]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

## We can't do these operations with matrices or vectors of different sizes but we can do it with a scalar 

## Transposing a vector
### the values do not change or transform, they just change their positions

In [13]:
A = np.array([[5,12,6], [-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [14]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [15]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [16]:
x.T

array([1, 2, 3])

In [17]:
x.shape

(3,)

In [19]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [20]:
x_reshaped.T

array([[1],
       [2],
       [3]])

## Multiplication
### We can get dot products (inner product) or Tensor products (outer products)
### the dot product is the sum of the products of the coresponding elements

In [21]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])
np.dot(x,y)

-66

## Multiplying matrices
### m* n can only be multiplied with n * k, second dimention of one of them needs to match the second dimension of the other, the output is an m * k matrix

### as a reminder: matrices are nothin more than a collection of vectors
### when we have a dot product we always multiply a row vector times a column vector

In [23]:
A = np.array([[5,12,6], [-3,0,14]])
B = np.array([[2,-1], [8,0], [3,0]])
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

## Vectorized code
